### ISSUE TITLE
No such file to load -- telegram_accouts_refresh_worker (LoadError)

### ISSUE THREAD

**Issue by denigmus** [southbridgeio/redmine_2fa#64]
```
thin start -e production
Using rack adapter
/usr/local/lib/ruby/gems/2.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require': No such file to load -- telegram_accouts_refresh_worker (LoadError)
        from /usr/local/lib/ruby/gems/2.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/lib/ruby/gems/2.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/lib/ruby/gems/2.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/lib/ruby/gems/2.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:360:in `require_or_load'
        from /usr/local/lib/ruby/gems/2.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:317:in `depend_on'
        from /usr/local/lib/ruby/gems/2.4/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:233:in `require_dependency'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/engine.rb:471:in `each'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/engine.rb:471:in `block in eager_load!'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/engine.rb:469:in `each'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/engine.rb:469:in `eager_load!'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/engine.rb:346:in `eager_load!'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/application/finisher.rb:56:in `each'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/lib/ruby/2.4/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/2.4/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.4/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.4/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.4/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/2.4/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/2.4/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/2.4/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/2.4/tsort.rb:205:in `tsort_each'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/lib/ruby/gems/2.4/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
        from /usr/local/www/redmine/config/environment.rb:14:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.4/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/local/lib/ruby/site_ruby/2.4/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/local/www/redmine/config.ru:3:in `block in <main>'
        from /usr/local/lib/ruby/gems/2.4/gems/rack-1.6.9/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/local/lib/ruby/gems/2.4/gems/rack-1.6.9/lib/rack/builder.rb:55:in `initialize'
        from /usr/local/www/redmine/config.ru:1:in `new'
        from /usr/local/www/redmine/config.ru:1:in `<main>'
        from /usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `eval'
        from /usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `load'
        from /usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/rack/adapter/loader.rb:42:in `for'
        from /usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/controllers/controller.rb:170:in `load_adapter'
        from /usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/controllers/controller.rb:74:in `start'
        from /usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
        from /usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
        from /usr/local/lib/ruby/gems/2.4/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
        from /usr/local/bin/thin:23:in `load'
        from /usr/local/bin/thin:23:in `<main>'

```

Could you advice what can be the problem?

ruby 2.4.4p296 
redmine-3.4.5

Plugins are cloned just few minutes ago

**Comment by funk-yourself** [comment]
It should be fixed in current version. Please, reopen if you're still experiencing this problem.
