### ISSUE TITLE
2FA - QRCode Error

### ISSUE THREAD

**Issue by haiopaii** [southbridgeio/redmine_2fa#83]
Hey guys,

when I try to login with a freshly created user, I get an internal error.
The error message is:

>   Rendering plugins/redmine_2fa/app/views/account/init_2fa.html.erb within layouts/base
>   Rendered plugins/redmine_2fa/app/views/account/_autologin.html.erb (0.5ms)
>   Rendered plugins/redmine_2fa/app/views/account/init_2fa/_google_auth_qr_code.html.erb (11.8ms)
>   Rendered plugins/redmine_2fa/app/views/account/init_2fa/_google_auth.html.erb (21.1ms)
>   Rendered plugins/redmine_2fa/app/views/account/init_2fa.html.erb within layouts/base (32.1ms)
> Completed 500 Internal Server Error in 426ms (ActiveRecord: 7.0ms)
> 
> NameError (uninitialized constant RQRCode::QRCodeRunTimeError):
> 
> plugins/redmine_2fa/lib/redmine_2fa/patches/account_controller_patch/second_authentication_init.rb:15:in `rescue in password_authentication'
> plugins/redmine_2fa/lib/redmine_2fa/patches/account_controller_patch/second_authentication_init.rb:11:in `password_authentication'
> plugins/redmine_2fa/lib/redmine_2fa/patches/account_controller_patch/second_authentication_prepare.rb:16:in `password_authentication'
> app/controllers/account_controller.rb:211:in `authenticate_user'
> app/controllers/account_controller.rb:38:in `login'
> plugins/redmine_reporting/lib/redmine_reporting/sweeper.rb:23:in `around'
> plugins/redmine_reporting/lib/redmine_reporting/sweeper.rb:23:in `around'
> lib/redmine/sudo_mode.rb:63:in `sudo_mode'
> plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'

Gem Versions:
`rqrcode (1.1.2)
rqrcode_core (0.1.1, 0.1.0)`

Ruby: 2.3.3
Rails: 5.2.2
Redmine: 4.0.2

So it is not possible to rollout new users unless I set "Ignore 2FA"

Any suggestions?

**Comment by haiopaii** [comment]
Found the error.

The new gem rqrcode is the problem.
After installing rqrcode 0.10.1 it works
